### ISSUE TITLE
Retry fails with ObjectDisposedException for System.Net.Http.StreamContent

### ISSUE THREAD

**Issue by blessthecore** [oracle/oci-dotnet-sdk#99] opened 2022-01-13 20:33 UTC
Code example to reproduce the issue:

public static string CreateKeyTest()
{

    RetryConfiguration retry = new Oci.Common.Retry.RetryConfiguration
    {
        GetNextDelayInSeconds = DelayStrategy.GetExponentialDelayInSeconds,
        TotalElapsedTimeInSecs = 30,
        MaxAttempts = 10,
        RetryableStatusCodeFamilies = new List<int>(new int[] { 1, 2, 3, 4, 5 })
    };

    CreateKeyDetails createKeyDetails = new CreateKeyDetails
    {
        CompartmentId = compartment_id,
        DisplayName = "test key",
        KeyShape = new KeyShape
        {
            Algorithm = KeyShape.AlgorithmEnum.Rsa,
            Length = 384
        },
        ProtectionMode = CreateKeyDetails.ProtectionModeEnum.Software
    };

    CreateKeyRequest createKeyRequest = new CreateKeyRequest
    {
        CreateKeyDetails = createKeyDetails
    };

    using (KmsManagementClient kmsManagementClient = new KmsManagementClient(new ConfigFileAuthenticationDetailsProvider("DEFAULT"), new ClientConfiguration(), your_key_vault_management_endpoint))
    {
        Task<CreateKeyResponse> createKeyResponse = kmsManagementClient.CreateKey(createKeyRequest, retry);
        createKeyResponse.Wait();
        return createKeyResponse.Result.Key.Id;
    }
}

To simulate the error and to trigger the retry provide an incorrect "compartment_id".
The very first retry will fail with ObjectDisposedException in SigningUtils.cs:line 105

Stack trace:

at System.Net.Http.HttpContent.CheckDisposed()\r\n   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)\r\n   
at Oci.Common.Http.Signing.Internal.SigningUtils.<ReadRequestBody>d__3.MoveNext() 
in Common\\Src\\Http\\Signing\\Internal\\SigningUtils.cs:line 105"

**Comment by github-anurag** [comment] 2022-01-13 20:58
@blessthecore 
Thank you for reporting this error. We will look into this and get back to you.

**Comment by blessthecore** [comment] 2022-01-14 01:37
The cause could be in CloneHttpRequestMessage method in  [\Common\Src\Utils\HttpUtils.cs ](https://github.com/oracle/oci-dotnet-sdk/blob/master/Common/Src/Utils/HttpUtils.cs) line 151: 
clone.Content = request.Content;

"Content" of an original request gets disposed after the first unsuccessful http request. 
The cloned one tries to operate on the disposed Content and this throws an exception.

**Comment by blessthecore** [comment] 2022-01-14 14:10
@github-anurag
The root cause could be in the following:
MakeRetryingCall in https://github.com/oracle/oci-dotnet-sdk/blob/master/Common/Src/Retry/GenericRetrier.cs clones the original request using CloneHttpRequestMessage utility method.

Notice in CloneHttpRequestMessage method in https://github.com/oracle/oci-dotnet-sdk/blob/master/Common/Src/Utils/HttpUtils.cs line 151:

clone.Content = request.Content;

"Content" is disposable. Content of the original request gets disposed after the first unsuccessful http request.
On the retry, the cloned request tries to operate on the disposed Content and this throws an exception.

**Comment by github-anurag** [comment] 2022-01-14 15:33
@blessthecore 
I think you are correct. I will try to reproduce this and find a fix for this.

**Comment by github-anurag** [comment] 2022-01-18 16:38
@blessthecore 
I am not able to Reproduce the issue. An incorrect compartment_id leads to the following error:-
```
2022-01-18 10:35:46.7979|ERROR|Oci.Common.ClientBase|CreateKey failed with error: The compartmentId must be an ocid.
```

**Comment by github-anurag** [comment] 2022-01-18 18:14
@blessthecore 
I have a potential fix that would Involve changing the line:-
```
clone.Content = request.Content;
```
to:-
```
// Copy the request's content (via a MemoryStream) into the cloned object
var ms = new MemoryStream();
await request.Content.CopyToAsync(ms).ConfigureAwait(false);
ms.Position = 0;
clone.Content = new StreamContent(ms);
// Copy the content headers
if (request.Content.Headers != null)
{
    foreach (var header in request.Content.Headers)
    {
        clone.Content.Headers.Add(header.Key, header.Value);
    }
}
```
However, I wanted to verify if this fix works before I make the changes.

**Comment by github-anurag** [comment] 2022-02-01 17:31
@blessthecore 
This issue was fixed with release `30.3.0`. Please feel free to re-open this issue if you still see this issue in the new release.

**Closed by github-anurag** 2022-02-01 17:31 UTC
Labels: SDK

**Comment by blessthecore** [comment] 2022-02-01 17:45
@github-anurag Thank you!
