### ISSUE TITLE
Call to HeadObject on large file causes exception "Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647."

### ISSUE THREAD

**Issue by cohibasuper** [oracle/oci-dotnet-sdk#88] opened 2021-11-05 14:04 UTC
Apologies if I am using this API function incorrectly, but to me it seems a call to HeadObject() to determine the size of a file on OCI object storage is allocating memory for the entire file. If this is a large file it causes the exception "Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647." Small files work fine but I cannot set the buffer big enough in ClientConfiguration.ResponseContentBufferBytes for larger files (also I don't want to as I don't see why I need to allocate this buffer just to do a HEAD call).

            using (var osClient = new ObjectStorageClient(device.ToAuthProvider(),
                TransferOciSystem.ClientConfigFactory.GetClientConfig()))
            {
                var headRequest = new HeadObjectRequest
                {
                    BucketName = device.Bucket,
                    ObjectName = fnet.FILENAME,
                    NamespaceName = device.Credentials.Namespace
                };

                var headResponse = await osClient.HeadObject(headRequest);

                if (headResponse.ContentLength == null)
                {
                    return new ActionResult
                    {
                        IsTaskComplete = true,
                        Error = "Failed to get file length"
                    };
                }

                var fileLength = headResponse.ContentLength.Value;
        }

**Comment by github-anurag** [comment] 2021-11-05 15:14
@cohibasuper 
This API call shouldn't allocate memory to any buffer. We just call the Object Storage API and get a response object from it which is passed back to the caller. 
What is the size of the large file where you see this issue? I would like to try this on end and see if I can reproduce the issue.

**Comment by github-anurag** [comment] 2021-11-05 16:07
@cohibasuper 
I am able to run a HeadObject request on a 3.34 GB file without any issues. Can you check once more if you are encountering this issue for this API and not somewhere else?

**Comment by cohibasuper** [comment] 2021-11-05 16:48
@github-anurag we are dealing with large video files. The one I am using to test which shows the issue is a 10.4GB MXF (Material Exchange Format) file. I will check and see if I get the issue with one of similar size to yours.

**Comment by github-anurag** [comment] 2021-11-05 16:52
@cohibasuper 
Can you enable TRACE level logging and paste the logs here?
Refer the logging section in: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/dotnetsdkgettingstarted.htm

**Comment by cohibasuper** [comment] 2021-11-05 20:35
```
2021-11-05 20:26:32.9418|INFO|Oci.Common.Utils.RetryUtils|Environment Variable OCI_SDK_DEFAULT_RETRY_ENABLED not found or is not a bool, setting Global Default retry enabled as: False
2021-11-05 20:26:33.0209|DEBUG|Oci.Common.Auth.CustomerAuthenticationDetailsProvider|Using keyId: XXXXXX
2021-11-05 20:26:33.0916|DEBUG|Oci.Common.Auth.CustomerAuthenticationDetailsProvider|Using keyId: XXXXXX
2021-11-05 20:26:33.0916|DEBUG|Oci.Common.Auth.CustomerAuthenticationDetailsProvider|Using keyId: XXXXXX
2021-11-05 20:26:33.1099|INFO|Oci.Common.ClientBase|Setting endpoint to https://objectstorage.eu-frankfurt-1.oraclecloud.com
2021-11-05 20:26:33.1099|DEBUG|Oci.Common.Http.RestClient|Setting endpoint to: https://objectstorage.eu-frankfurt-1.oraclecloud.com
2021-11-05 20:26:34.3012|TRACE|Oci.Common.RegionalClientBase|Called headObject
2021-11-05 20:26:34.3192|DEBUG|Oci.Common.Converter|Adding path parameter namespaceName: XXXXXX
2021-11-05 20:26:34.3614|DEBUG|Oci.Common.Converter|Adding path parameter bucketName: XXXXXX
2021-11-05 20:26:34.3614|DEBUG|Oci.Common.Converter|Adding path parameter objectName: File_3stereo.mxf
2021-11-05 20:26:34.4626|DEBUG|Oci.Common.Http.RestClientHandler|Dumping HttpRequest:
Method: HEAD, RequestUri: 'https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/XXXXXX/b/XXXXXX/o/File_3stereo.mxf', Version: 1.1, Content: <null>, Headers:

  Accept: application/json
  User-Agent: Oracle-DotNetSDK/28.1.0
  User-Agent: (Win32NT/6.2.9200.0; .NET Framework 4.8.4420.0)
  Date: Fri, 05 Nov 2021 20:26:34 GMT
  host: objectstorage.eu-frankfurt-1.oraclecloud.com
  authorization: Signature version="1",headers="date (request-target) host",keyId="XXXXXX",algorithm="rsa-sha256",signature=XXXXXX"
}
2021-11-05 20:26:34.8719|ERROR|Oci.Common.RegionalClientBase|HeadObject failed with error: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
2021-11-05 20:26:34.9243|INFO|Oci.Common.ClientBase|Disposing rest client.
```

Let me know if you need anything else.

**Comment by github-anurag** [comment] 2021-11-05 22:03
@cohibasuper 
It looks like this is a known issue with .NET HTTP library:-
https://github.com/mono/mono/issues/14214 
https://stackoverflow.com/questions/18720435/httpclient-buffer-size-limit-exceeded

The suggested workaround here is to pass a `HttpCompletionOption.ResponseHeadersRead` option while calling `SendAsync` function of `System.Net.Http.HttpClient`

Unfortunately, we currently do not have a means to pass this option in the .NET SDK. We will need to work on a fix on how to do this.

In the meanwhile, there is a temporary workaround that you can try and see if it works. While creating the `ClientConfiguration` , you can set the property `ResponseContentBufferBytes` to a value greater than the file size you are calling the HeadObject on. I haven't tested this workaround as I have not been able to reproduce the issue yet.

**Comment by cohibasuper** [comment] 2021-11-08 10:06
Hi @github-anurag. As stated in my original comment I cannot set the ResponseContentBufferBytes big enough. Even if I set it to int.Max() (which is its default if you don't set it) this still is not large enough for the file. If I try and set it bigger I get "Buffering more than 2147483647 bytes is not supported." Also I don't want my application to swallow up 10GB+ of memory to do a HEAD call!

**Comment by cohibasuper** [comment] 2021-11-08 10:22
I think for workaround I will either need to use CLI or make the HTTP call myself so I can set HttpCompletionOption.ResponseHeadersRead

**Comment by github-anurag** [comment] 2021-11-08 11:17
@cohibasuper 
As I mentioned this is specific to .NET HTTP library which is probably present in some particular .NET Frameworks. If you are going to use CLI you won't need to pass this option. Another alternative can be to use another .NET Target framework like the newly released .NET 5.0 to see if that can resolve the issue.
To enable users to provide HttpCompletionOption.ResponseHeadersRead in .NET SDK would require an interface change on all requests and may take some time to implement.

**Comment by github-anurag** [comment] 2022-01-11 20:15
@cohibasuper 
This issue is now resolved with .NET SDK in the release `30.0.0`
Users can now pass in the HttpCompletionOption.ResponseHeadersRead as an optional parameter. So in your code above you can use:-
```
var headResponse = await osClient.HeadObject(getObjectObjectRequest, completionOption:HttpCompletionOption.ResponseHeadersRead);
```
PS: You will need to add `using System.Net.Http` to import the HttpCompletionOption.

**Closed by github-anurag** 2022-01-11 20:15 UTC
Labels: SDK
