### ISSUE TITLE
System.PlatformNotSupportedException: Operation is not supported on this platform

### ISSUE THREAD

**Issue by anuj-dwivedi** [oracle/oci-dotnet-sdk#16] opened 2020-09-13 20:42 UTC
Hi,

Please comment out/remove line#21 (https://github.com/oracle/oci-dotnet-sdk/blob/56b2b30c209d9ca716c2a45a4b9f7314a4ac95ba/Common/Src/Http/RestClientHandler.cs#L21) in Oci.Common.Http.RestClientHandler. It's not needed for .Net 4.6 and above and causes System.PlatformNotSupportedException when SDK is used with .Net Framework (pre 4.7.2) target applications. 

You may access relevant API doc here - https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.sslprotocols?view=netframework-4.7.1#System_Net_Http_HttpClientHandler_SslProtocols

Thanks,
Anuj

**Comment by varunmankal** [comment] 2020-09-22 18:20
Hi @anuj-dwivedi , 

The issue is fixed in today's release: https://github.com/oracle/oci-dotnet-sdk/releases/tag/v4.5.0. 

Thanks for trying this out.

**Closed by varunmankal** 2020-09-22 18:20 UTC
Labels: SDK
