### ISSUE TITLE
DataSafe-models-LifecycleState invalid enum value

### ISSUE THREAD

**Issue by jbcintra** [oracle/oci-dotnet-sdk#108] opened 2022-03-07 16:48 UTC
Hi,
The DataSafe model for LifecycleState has an enum value "NA", the output value from the API is "NEEDS_ATTENTION", which is causing and error in conversion to type LifecycleState, the requested value was not found.

This is referenced when trying to download target databases.

**Comment by github-anurag** [comment] 2022-03-07 16:56
@jbcintra 
When do you get the output as "NEEDS_ATTENTION" ? Is it while using an API while downloading Target Database? If so, which API are you using?

**Comment by jbcintra** [comment] 2022-03-07 17:07
Great, thanks @github-anurag :)

**Comment by github-anurag** [comment] 2022-03-10 17:18
@jbcintra 
Looks like you were using the incorrect model for LifecycleState. You need to use the [TargetDatabaseLifecycleState](https://github.com/oracle/oci-dotnet-sdk/blob/master/Datasafe/models/TargetDatabaseLifecycleState.cs) for the ListTargetDatabases API instead which has the required enum value "NEEDS_ATTENTION", defined under it.

If this resolves your issue then please close the ticket :)

**Comment by jbcintra** [comment] 2022-03-15 17:26
Hi @github-anurag, just got to look back at this. That code above is returning objects, which I'm outputting as JSON. I'm not passing them into other objects, translating or reading them.  So it is just the JSON object that fails with the error.  

I've just re-ran the code, the error happens in the "var responseEnum" line detailed above, so definitely not me reading/manipulating any output state.

**Comment by jbcintra** [comment] 2022-03-15 17:34
Hi @github-anurag, just got to look back at this. That code above is returning objects, which I'm outputting as JSON. I'm not passing them into other objects, translating or reading them.  So it is just the JSON object that fails with the error.  

I've just re-ran the code, the error happens in the "var responseEnum" line detailed above, so definitely not me reading/manipulating any output state.

**Comment by github-anurag** [comment] 2022-03-15 17:58
@jbcintra 
Did you upgrade the SDK version? If so, what version did you upgrade from? Does this code still work in the older version?

**Comment by jbcintra** [comment] 2022-03-15 18:07
It's on 32.2.0, I'd likely have to go back a few versions, which then wouldn't have all the new models in.

**Comment by github-anurag** [comment] 2022-03-15 18:53
@jbcintra 
Found the root cause for this issue:-

The model [TargetDatabaseSummary](https://github.com/oracle/oci-dotnet-sdk/blob/master/Datasafe/models/TargetDatabaseSummary.cs#L97) has the property `LifecycleState` defined with the type [LifecycleState](https://github.com/oracle/oci-dotnet-sdk/blob/master/Datasafe/models/LifecycleState.cs). However, the type should have been of type [TargetDatabaseLifecycleState](https://github.com/oracle/oci-dotnet-sdk/blob/master/Datasafe/models/TargetDatabaseLifecycleState.cs)

The only difference between the two is the enum :-
```
[EnumMember(Value = "NA")] Na

v/s

[EnumMember(Value = "NEEDS_ATTENTION")] NeedsAttention,
```

Unfortunately, the only workaround for this right now would be to somehow change the `LifeCycleState` of the TargetDatabase with the state `NEEDS_ATTENTION` on your end.

The reason why your code worked before was probably no TargetDataBase was in this state.

**Comment by jbcintra** [comment] 2022-03-15 19:34
thanks @github-anurag !  i might see if I can do a workaround in the interim

**Comment by github-anurag** [comment] 2022-04-05 22:10
@jbcintra 
This issue has been resolved in the release today. Please feel free to re-open this if you see it again.

**Closed by github-anurag** 2022-04-05 22:10 UTC
Labels: Data Safe

**Comment by jbcintra** [comment] 2022-04-06 07:05
Thanks @github-anurag, I've just updated the components and it's working, outputting "NeedsAttention" in the LifecycleState and no longer failing.
